services:

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    env_file:
      - ./Backend/.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  
      - ./Backend/db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s
    restart: always

  backend:
    build:
      dockerfile: ./Backend/Dockerfile
      context: .
    container_name: backend_container
    ports:
      - "5001:5001"
    env_file:
      - ./Backend/.env
    environment:
      DB_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./Backend:/app/Backend
    restart: always

  frontend:
    build:
      dockerfile: ./Frontend/Dockerfile
      context: .
    container_name: frontend_container
    ports:
      - "5000:5000"
    env_file:
      - ./Frontend/.env
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
      FLASK_DEBUG: 1
      BACKEND_URL: http://backend_container:5001
    depends_on:
      - backend
    volumes:
      - ./Frontend:/app
    restart: always

volumes:
  db_data: