version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    env_file:
      - ./Backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: HotelBruno
    ports:
      - "3306:3306"
    volumes:
      - ./Backend/db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: always

  backend:
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: backend_container
    ports:
      - "5001:5001"
    environment:
      DB_HOST: localhost
      DB_USER: hoteluser
      DB_PASSWORD: juano
      DB_NAME: HotelBruno
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5001
    depends_on:
      - mysql
    volumes:
      - ./Backend:/app
    restart: always

  frontend:
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: frontend_container
    ports:
      - "5000:5000"
    env_file:
      - ./Frontend/.env
    environment:
      FLASK_APP: app.py
      FLASK_RUN_PORT: 5000
      FLASK_DEBUG: 1
    depends_on:
      - backend
    volumes:
      - ./Frontend:/app
    restart: always

volumes:
  db_data: