version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    env_file:
      - ./Backend/.env
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: HotelBruno
    ports:
      - "5002:5002"
    volumes:
      - ./Backend/db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s
    restart: always

  backend:
    build: 
      dockerfile: ./Backend/Dockerfile
      context: .
    container_name: backend_container
    ports:
      - "5001:5001"
    env_file:
      - ./Backend/.env
    environment:
      DB_HOST: mysql
      DB_USER: hoteluser
      DB_PASSWORD: admin
      DB_NAME: HotelBruno
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5001
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./Backend:/app
    restart: always

  frontend:
    build: 
      dockerfile: ./Frontend/Dockerfile
      context: .
    container_name: frontend_container
    ports:
      - "5000:5000"
    env_file:
      - ./Frontend/.env
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
      FLASK_DEBUG: 1
    depends_on:
      - backend
    volumes:
      - ./Frontend:/app
    restart: always

volumes:
  db_data: